# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master


pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  jmeterParserDirectory:  '$(Build.SourcesDirectory)/JmeterResultsCsvParser'
  jmeterParserProjectName: 'JmeterResultsCsvParser.csproj'
  jmeterParserProject: '$(jmeterParserDirectory)/$(jmeterParserProjectName)' 
  jmeterParserPublishDirectory: '$(jmeterParserDirectory)/obj/publish'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  displayName: 'Build Jmeter Parser'
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration Release'

- task: DotNetCoreCLI@2
  displayName: Publish Jmeter Parser
  inputs:
    workingDirectory: $(jmeterParserDirectory)
    command: publish
    arguments: "--configuration Release --output $(jmeterParserPublishDirectory)"
    projects: |
      $(jmeterParserProject)
    publishWebProjects: false
